name: developToMain

on:
  push:
    branches:
      - develop
jobs:
  developToMain:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Ruby 3.1
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
      - name: Execute git-pr-release
        env:
          GIT_PR_RELEASE_BRANCH_PRODUCTION: main
          GIT_PR_RELEASE_BRANCH_STAGING: develop
          GIT_PR_RELEASE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_PR_RELEASE_TEMPLATE: '.github/.git-pr-template.erb'
        run: |
          gem install git-pr-release -v "0.6.0"
          git-pr-release || echo "Done."
      - name: Slack
        uses: 8398a7/action-slack@v3
        if: always()
        with:
          status: custom
          custom_payload: |
            {
              text: "Release PR"
              attachments: [{
                color: '${{ job.status }}' === 'success' ? 'good' : '${{ job.status }}' === 'failure' ? 'danger' : 'warning',
                title: "${{ github.repository }} #${{ github.event.number}}",
                title_link: "${{ github.event.pull_request.html_url }}",
                text: "${{ github.event.pull_request.title }} #${{ github.event.number }}",
                fields: [{
                  title: "Status",
                  value: "${{ job.status }}",
                  short: true
                }, {
                  title: "Log",
                  value: `<${process.env.GITHUB_SERVER_URL}/${{ github.repository }}/actions/runs/${{ github.run_id }}|Checks URL>`,
                  short: true
                }]
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
