name: developToMain

on:
  push:
    branches:
      - develop
jobs:
  developToMain:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Ruby 3.1
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
      - name: Execute git-pr-release
        env:
          GIT_PR_RELEASE_BRANCH_PRODUCTION: main
          GIT_PR_RELEASE_BRANCH_STAGING: develop
          GIT_PR_RELEASE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_PR_RELEASE_TEMPLATE: '.github/.git-pr-template.erb'
        run: |
          gem install git-pr-release -v "0.6.0"
          git-pr-release || echo "Done."
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2.0.2
        env:
          SLACK_CHANNEL: dev_pr_camel_batch
          SLACK_TITLE: Release PR
          SLACK_COLOR: good
          SLACK_MSG_AUTHOR: $GITHUB_ACTOR
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}